### PR TITLE
fix: update eslint-plugin-testing-library to v5

### PR DESCRIPTION
**Pull request by Belco90**
Breaking changes:
- rename `no-debug` to `no-debugging-utils`

### CODE REVIEW

**Comment by AriPerkkio** [comment]
Thanks @Belco90! I was planning to study this next week so your timing is perfect. ❤️ 🎉 

However while testing this locally I'm seeing an error. Should `eslint-plugin-testing-library` support ESLint v8 yet?

```sh
/workspaces/eslint-remote-tester/ci (master ✗) $ yarn lint --config ./plugin-configs/eslint-plugin-testing-library.config.js 
yarn run v1.22.5
$ eslint-remote-tester --config ./plugin-configs/eslint-plugin-testing-library.config.js
Configuration validation errors:
- eslintrc: Failed to load plugin 'testing-library' declared in 'CLIOptions': Class extends value undefined is not a constructor or null
error Command failed with exit code 1.
```

**Comment by Belco90** [comment]
What a weird error. V5 of the plugin works with ESLint v8 (I'm using this combination in a personal project). Not sure what could cause this.

**Comment by AriPerkkio** [comment]
Oh right, it is actually working. There is a cleanup step run on CI which gets rid of projects internal dependencies, so that we only have the ones defined in `ci/package.json` when running the tests. These weird errors come up when we have multiple versions of `eslint` available. 

https://github.com/AriPerkkio/eslint-remote-tester/blob/71ef946d77c5b85a883a69a2e0f56cd1d436dd1c/.github/workflows/lint-eslint-plugin-testing-library.yml#L42-L43

Once running the cleanup in local environment everything worked fine. Also here is a on-going CI run. https://github.com/AriPerkkio/eslint-remote-tester/runs/4120468448?check_suite_focus=true

In 6 hours the badge should turn green - hopefully. 😄

**Comment by Belco90** [comment]
Awesome! Thanks for sorting this out so quickly.

**Comment by Belco90** [comment]
All green now by the way 💪

**Pull request merged**
