### PR TITLE
chore: prettify codebase

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Trying to work on this repo, my IDE gave me errors constantly about files not complying with the prettier config

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@AriPerkkio I resolved the conflicts

**Comment by AriPerkkio** [comment]
Thanks, good catch. I've completely missed `yml|md` files. 

Is your IDE reporting these as ESLint errors or do you have some prettier plugin? I wonder why my vscode setup doesn't raise these errors.

Also I'd like to have these formatted by `lint-staged`. Not sure why this is not working:
```

**Comment by MichaelDeBoey** [comment]
@AriPerkkio It's probably due to the fact that I indeed have a Prettier plugin in my IDE

I've added the affected files to `lint-staged`

**Review by AriPerkkio — APPROVED** [review]

**Comment by AriPerkkio** [comment]
Thanks!

**Pull request merged**
