### PR TITLE
fix: use react@17

### PR DESCRIPTION
**Pull request by SimenB**
Similar to https://github.com/vadimdemedes/ink/pull/516

### CODE REVIEW

**Comment by AriPerkkio** [comment]
Pending for the ink's version bumps. The react versions must match 100%, ref. https://github.com/AriPerkkio/eslint-remote-tester/pull/302.

**Comment by SimenB** [comment]
Ink is wrong 🤷 and specifying `17.0.2` is within Ink's peer range

**Comment by AriPerkkio** [comment]
> specifying `17.0.2` is within Ink's peer range

Ah, that's right. This should be fine then. 

I'll do some testing before merging this just to be sure.

**Comment by AriPerkkio** [comment]
Current version requirement is indeed incorrect. While `npm` is able to resolve correct version, `yarn` ends up with incorrect one. 

```
$ yarn
yarn install v1.22.5
...
warning "eslint-remote-tester > ink > react-reconciler@0.26.2" has incorrect peer dependency "react@^17.0.2".

$ yarn why react
yarn why v1.22.5
...
=> Found "react@18.0.0"
info Reasons this module exists
   - "eslint-remote-tester" depends on it
   - Hoisted from "eslint-remote-tester#react"
```

```
$ npm why react

react@17.0.2
node_modules/react
  react@">=16.8.0" from eslint-remote-tester@2.1.3
  node_modules/eslint-remote-tester
    eslint-remote-tester@"^2.1.3" from the root project
  peer react@">=16.8.0" from ink@3.2.0
  node_modules/ink
    ink@"^3.2.0" from eslint-remote-tester@2.1.3
    node_modules/eslint-remote-tester
      eslint-remote-tester@"^2.1.3" from the root project
  peer react@"^17.0.2" from react-reconciler@0.26.2
  node_modules/react-reconciler
    react-reconciler@"^0.26.2" from ink@3.2.0
    node_modules/ink
      ink@"^3.2.0" from eslint-remote-tester@2.1.3
      node_modules/eslint-remote-tester
        eslint-remote-tester@"^2.1.3" from the root project
```

**Comment by AriPerkkio** [comment]
Thanks!

**Pull request merged**
